### ISSUE TITLE
New op: fitted

### ISSUE THREAD

**Issue by pkieltyka** [pressly/imgry#10]
<img width="876" alt="screen shot 2015-11-18 at 2 19 39 pm" src="https://cloud.githubusercontent.com/assets/18831/11251477/7497237a-8dff-11e5-8d88-dc71ef03d019.png">

**Comment by pkieltyka** [comment]
note: the `canvas` query param is a new addition to the existing api

**Comment by alinz** [comment]
@pkieltyka it seems logic is correct.
