### ISSUE TITLE
Imagick reference is broken

### ISSUE THREAD

**Issue by xiam** [pressly/imgry#18]
Hey @pkieltyka, it looks like, with your latest commit, the `github.com/gographics/imagick` was updated to a reference that does not exist:

```git diff a983e5c52dd277be3e78a150828fd4cf2805c6dd abd012e0f4c546fc0394e3ba1d1ccb24e32021d4```

And now the `make deps` script fails:

```
# cd /home/vagrant/go/src/github.com/gographics/imagick; git checkout 5f86f7c1a891
error: pathspec '5f86f7c1a891' did not match any file(s) known to git.
```

Probably glock failed to sync dependencies for some reason?

**Comment by pkieltyka** [comment]
Hmm.. yes, if you run update-deps.. make sure you dont update the gographic/imagick in Glockfile or vendor/  .. because I'm using a fork of the imagick package for now until a PR I am waiting for gets merged.
